# Exercices NumPy 

<span style="color:red">Réalisation de tous les exercices sans utiliser de boucles.</span>
---

In [26]:
%pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 1.3 MB/s eta 0:00:10
   -- ------------------------------------- 0.8/12.6 MB 1.5 MB/s eta 0:00:09
   ----- ---------------------------------- 1.6/12.6 MB 2.3 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.6 MB 3.0 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.6 MB 3.3 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 3.3 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.6 MB 4.6 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.6 MB 5.8 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 6.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# import numpy as np

# # Configuration de la précision d'affichage
# np.set_printoptions(precision=2, suppress=True)
# print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Exercice 1 : Création et restructuration d'un tableau (1D → 2D)

**Objectif :**
1. Créez un vecteur 1D contenant les entiers de 1 à 20.
2. Transformez-le en une matrice 2D de dimensions $4 \times 5$.

In [ ]:
import numpy as np

tab = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

array_tab = np.array(tab)

matrice = array_tab.reshape(4, 5) #(linge,colunm)

print("new Matrice :\n")
print(matrice)

print("new Matrice :\n")
partie1=matrice[ : ,0:3]
print(partie1)

new Matrice :

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
new Matrice :

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]]


## Exercice 2 : Extraction par masque booléen (1D)

**Objectif :**
Soit un vecteur 1D de 15 nombres aléatoires entre 0 et 50. Extrayez tous les éléments strictement supérieurs à 25 **ET** pairs.

In [130]:
import numpy as np

vect=np.random.randint(0,51,15)
print(f"{vect} \n")

result =vect [(vect >25) &  (vect % 2==0)]
print(f"{result} \n")



[ 3 33 26 10 47 37 23 20 24 11 29  7 31 40 31] 

[26 40] 



## Exercice 3 : Inversion et inversion par colonnes (1D et 2D)

**Objectif :**
1. Inversez l'ordre des éléments d'un vecteur 1D de taille 10.
2. Soit une matrice $4 \times 4$, inversez l'ordre de ses colonnes (la dernière colonne devient la première).

In [149]:
# VOTRE CODE ICI
import numpy as np

vect1=np.arange(10)
print(f"{vect1}")
vect_resultat=vect1[::-1]

print(f"{vect_resultat}")


[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


## Exercice 4 : Statistique par axe (2D)

**Objectif :**
Soit une matrice $5 \times 3$ d'entiers aléatoires entre 1 et 100.
1. Calculez la moyenne globale de la matrice.
2. Calculez la somme des éléments pour chaque **colonne**.
3. Obtenez la valeur maximale pour chaque **ligne**.

In [407]:
import numpy as np
import random

l = np.array([[random.randint(1, 100) for j in range(3)] for i in range(5)])

matrice = l.reshape(5, 3)
sum=0
so=0
for i in range(3) :
    so=0
    for j in range(5) :
        sum=sum+ matrice[j][i]
        so=so+matrice[j][i]

   
moyenne=sum/15  
somme_colonnes = np.sum(matrice, axis=0)
somme_lignes = np.sum(matrice, axis=1)

print(somme_colonnes)     
print(somme_lignes)     

print(f"{matrice} and his global moyenne is : {moyenne}")


[310 207 214]
[102 169 183 134 143]
[[71  9 22]
 [87 12 70]
 [86 70 27]
 [29 52 53]
 [37 64 42]] and his global moyenne is : 48.733333333333334


## Exercice 5 : Remplacement des valeurs manquantes (1D / 2D)

**Objectif :**
Soit le tableau : `arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])`.
Remplacez toutes les valeurs `NaN` par la moyenne des valeurs non manquantes du tableau.

In [416]:
# VOTRE CODE ICI
import numpy as np
arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

moyenne=np.nanmean(arr)

arr[np.isnan(arr)]=moyenne

print(arr)

[1.   2.   3.25 4.   3.25 6.  ]


## Exercice 6 : Concaténation et empilement (2D)

**Objectif :**
Soit deux matrices $A$ et $B$ de dimensions $3 \times 2$.
1. Empilez-les verticalement pour obtenir une matrice $6 \times 2$.
2. Empilez-les horizontalement pour obtenir une matrice $3 \times 4$.

In [429]:
# VOTRE CODE ICI
import numpy as np

a=[[2,5,8],[2,9,7]]
b=[[1,3,7],[0,12,9]]

c=np.hstack((a,b))
d = np.vstack((a, b))

print(c)


[[ 2  5  8  1  3  7]
 [ 2  9  7  0 12  9]]


## Exercice 7 : Recherche d'indices spécifiques (`np.where`) (1D)

**Objectif :**
Soit un vecteur 1D de 12 valeurs réelles. Récupérez les **indices** (et non les valeurs) de tous les éléments compris entre 10 et 20 inclus.

In [441]:
# VOTRE CODE ICI
import numpy as np

arr = np.array([5, 12, 8, 15, 22, 10, 18, 25, 14, 7, 20, 30])

indices=np.where((arr>10) & (arr<=20))

print(indices)

(array([ 1,  3,  6,  8, 10]),)


## Exercice 8 : Calcul de la diagonale et trace (2D)

**Objectif :**
Générez une matrice carrée $4 \times 4$ d'entiers.
1. Extrayez les éléments de la diagonale principale sous forme de vecteur 1D.
2. Calculez la somme de ces éléments (la trace) en utilisant la fonction NumPy dédiée.

In [5]:
# VOTRE CODE ICI
import numpy as np

matrice = np.random.randint(1, 100, (4, 4))
print(matrice)

diagonale = np.diag(matrice)
print(diagonale)
# trace = np.trace(matrice)

# print(trace)

[[18 40 53 49]
 [41 69 41 73]
 [37 34  7 96]
 [86 11 21  7]]
[18 69  7  7]


## Exercice 9 : Masquage conditionnel & Remplacement rapide (1D)

**Objectif :**
Créez un vecteur 1D de 20 entiers aléatoires entre -10 et 10. Sans utiliser de boucle for ni d'instructions if, remplacez tous les nombres négatifs impairs par leur carré, et tous les nombres positifs pairs par 0.

In [ ]:
# VOTRE CODE ICI

import numpy as np

arr = np.random.randint(-10, 11, 20)

arr[(arr < 0) & (arr % 2 != 0)] **= 2

arr[(arr > 0) & (arr % 2 == 0)] = 0

print(arr)





[ -2   9  -2   0   5  49 -10 -10  49  49   1   0  -4  25   1  -2  25   9
   9   0]


## Exercice 10 : Extraction par glissement / Fenêtres glissantes (1D)

**Objectif :**
Soit un vecteur 1D $V = [1, 2, 3, 4, 5, 6, 7, 8]$. Générez une matrice 2D représentant toutes les sous-fenêtres glissantes de taille 3 avec un pas (stride) de 1.Résultat attendu :$$\begin{bmatrix} 1 & 2 & 3 \\ 2 & 3 & 4 \\ 3 & 4 & 5 \\ \dots & \dots & \dots \end{bmatrix}$$

In [7]:
# VOTRE CODE ICI
import numpy as np

V = np.array([1, 2, 3, 4, 5, 6, 7, 8])

matrice = np.lib.stride_tricks.sliding_window_view(V, 3)

print(matrice)


[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]]


## Exercice 11 : Extraction des k plus grands éléments par ligne (2D)

**Objectif :**
Soit une matrice 2D de dimensions $6 \times 8$ remplie d'entiers aléatoires. Extrayez, pour chaque ligne, les 3 plus grandes valeurs et leurs indices respectifs, triés par ordre décroissant.

In [8]:
import numpy

arr=np.random.randint(1, 100, (6, 8))



print("Matrice :")
print(arr)

indices = np.argsort(arr, axis=1)

indices_3 = indices[:, -3:]

indices_3 = indices_3[:, ::-1]

valeurs_3 = np.take_along_axis(arr, indices_3, axis=1)

print("Les 3 plus grandes valeurs :")
print(valeurs_3)

print("Leurs indices :")
print(indices_3)

Matrice :
[[ 3 49 35 70  1 85 63 57]
 [81 10 92 82  9 96 77 72]
 [13 86 99  1 67 32 12 73]
 [92 22 36 83  4 57 89 61]
 [48 48 47 28  7 58 99 39]
 [58  9 95 86 97 15 32 54]]
Les 3 plus grandes valeurs :
[[85 70 63]
 [96 92 82]
 [99 86 73]
 [92 89 83]
 [99 58 48]
 [97 95 86]]
Leurs indices :
[[5 3 6]
 [5 2 3]
 [2 1 7]
 [0 6 3]
 [6 5 1]
 [4 2 3]]
